options:
  formatter: stylish
  merge-default-rules: false
files:
  include: '**/*.s+(a|c)ss'
rules:
  # Extends
  extends-before-mixins: 1
  extends-before-declarations: 1
  placeholder-in-extend: 1

  # Mixins
  mixins-before-declarations:
    - 1
    -
      exclude: [ 'media-query', 'mq', 'type-space', 'type-scale', 'rems', 'shadow']

  # Line Spacing
  one-declaration-per-line: 1
  empty-line-between-blocks: 1
  single-line-per-selector: 1

  # Disallows
  no-color-keywords: 1
  no-color-literals: 0
  no-css-comments: 0
  no-debug: 1
  no-duplicate-properties: 0
  no-empty-rulesets: 1
  no-extends: 0
  no-ids: 0
  no-important: 0
  no-invalid-hex: 1
  no-mergeable-selectors: 0
  no-misspelled-properties: 0
  no-qualifying-elements:
      - 1
      -
        allow-element-with-attribute: true

  no-trailing-zero: 1
  no-transition-all: 0
  no-url-protocols: 1
  no-vendor-prefixes: 0
  no-warn: 1
  property-units: 0

  # Nesting
  force-attribute-nesting: 0
  force-element-nesting: 0
  force-pseudo-nesting: 0

  # Name Formats
  class-name-format:
      - 1
      -
          convention: ^(?!\W)(\-?[a-z0-9]+[A-Z0-9]?[a-z0-9]*)*$
          convention-explanation: 'Classes formatting: .parent-child or parentName-child'

  function-name-format: 1
  id-name-format: 0
  mixin-name-format: 1

  placeholder-name-format: 0

  variable-name-format: 1

  # Style Guide
  bem-depth: 0
  border-zero: 1
  brace-style: 1
  clean-import-paths: 1
  empty-args: 1
  hex-length: 1
  hex-notation: 1

  #Indentation should be 4 spaces or 1 tab
  # An error in sass-lint prevents us from setting this
  indentation: 0
  leading-zero: 1
  nesting-depth: 1
  property-sort-order:
      - 1
      -
          order:
            - 'content'

            - 'display'
            - 'order'
            - 'flex'
            - 'flex-shrink'
            - 'flex-grow'
            - 'flex-direction'
            - 'flex-basis'
            - 'flex-wrap'
            - 'flex-flow'
            - 'justify-content'
            - 'align-content'
            - 'align-items'
            - 'position'
            - 'top'
            - 'right'
            - 'bottom'
            - 'left'

            - 'transform'

            - 'columns'
            - 'column-gap'
            - 'column-fill'
            - 'column-rule'
            - 'column-span'
            - 'column-count'
            - 'column-width'

            - 'float'
            - 'clear'

            - 'visibility'
            - 'opacity'
            - 'z-index'

            - 'margin'
            - 'margin-top'
            - 'margin-right'
            - 'margin-bottom'
            - 'margin-left'

            - 'outline'

            - 'border'
            - 'border-top'
            - 'border-right'
            - 'border-bottom'
            - 'border-left'
            - 'border-width'
            - 'border-top-width'
            - 'border-right-width'
            - 'border-bottom-width'
            - 'border-left-width'

            - 'border-style'
            - 'border-top-style'
            - 'border-right-style'
            - 'border-bottom-style'
            - 'border-left-style'

            - 'border-color'
            - 'border-top-color'
            - 'border-right-color'
            - 'border-bottom-color'
            - 'border-left-color'

            - 'border-radius'
            - 'border-top-left-radius'
            - 'border-top-right-radius'
            - 'border-bottom-left-radius'
            - 'border-bottom-right-radius'

            - 'padding'
            - 'padding-top'
            - 'padding-right'
            - 'padding-bottom'
            - 'padding-left'

            - 'width'
            - 'min-width'
            - 'max-width'

            - 'height'
            - 'min-height'
            - 'max-height'

            - 'overflow'
            - '_overflow'
            - 'clip'

            - 'background'
            - 'background-color'
            - 'background-image'
            - 'background-repeat'
            - 'background-position'
            - 'background-position-x'
            - 'background-position-y'
            - 'background-size'
            - 'cursor'

            - 'list-style'
            - 'caption-side'

            - 'table-layout'
            - 'border-collapse'
            - 'border-spacing'
            - 'empty-cells'

            - 'vertical-align'

            - 'text-align'

            - 'color'
            - 'line-height'
            - 'word-spacing'
            - 'letter-spacing'
            - 'white-space'
            - 'direction'

            - 'font'
            - 'font-family'
            - 'font-size'
            - 'font-weight'
            - 'font-smoothing'
            - 'font-style'

            - 'text-indent'
            - 'text-transform'
            - 'text-decoration'
            - 'text-rendering'
            - 'text-overflow'

            - 'quotes'

            - 'box-shadow'
            - 'text-shadow'

            - 'transition'
            - 'transition-property'
            - 'transition-duration'

            - 'animation'
            - 'animation-name'
            - 'animation-duration'
            - 'animation-timing-function'
            - 'animation-delay'
            - 'animation-iteration-count'
            - 'animation-direction'
            - 'animation-fill-mode'
            - 'animation-play-state'
  quotes: 1
  shorthand-values: 1
  url-quotes: 1
  variable-for-property: 1
  zero-unit: 1

  # Inner Spacing
  space-after-comma: 1
  space-before-colon: 1
  space-after-colon: 1
  space-before-brace: 1
  space-before-bang: 1
  space-after-bang: 1
  space-between-parens: 1
  space-around-operator: 0

  # Final Items
  trailing-semicolon: 1
  final-newline: 1
